### ISSUE TITLE
KeyboardEvent.keycode is deprecated

### ISSUE THREAD

**Issue by bigsaigon333** [ddongule/mandal-art#4]
Hi there!

I found KeyboardEvent.keycode is used in several files but according to MDN, KeyboardEvent.keycode is deprecated.

**So why don't we use KeyboardEvent.code rather than KeyboardEvent.keycode?**

[MDN - code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code)
[MDN - keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

**Comment by ddongule** [comment]
Hi! Thanks for reporting.
Fixed this Issue by [`2a29710`](https://github.com/ddongule/mandal-art/commit/2a29710a361ab08f9b4531233bfddb830838a492).
